# Generated by Django 3.1.6 on 2021-03-04 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(1, 'Политика'), (2, 'Общество'), (3, 'Экономика'), (4, 'Спорт')], db_index=True, verbose_name='Категория')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('short_description', models.CharField(max_length=500, verbose_name='Краткое описание')),
                ('full_description', models.CharField(max_length=3000, verbose_name='Полное описание')),
                ('news_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category')),
            ],
        ),
    ]
