# Generated by Django 3.1.6 on 2021-03-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210305_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.IntegerField(choices=[(1, 'red'), (2, 'green'), (3, 'blue'), (4, 'yellow')], verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
